// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDbContextNamespace;

#nullable disable

namespace assetTracking.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetNameSpace.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Motorola",
                            Model = "X3",
                            OfficeId = 1,
                            Price = 200m,
                            PurchaseDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Motorola",
                            Model = "X3",
                            OfficeId = 1,
                            Price = 400m,
                            PurchaseDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Motorola",
                            Model = "X2",
                            OfficeId = 1,
                            Price = 400m,
                            PurchaseDate = new DateTime(2020, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            Model = "Galaxy 10",
                            OfficeId = 2,
                            Price = 4500m,
                            PurchaseDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            Model = "Galaxy 10",
                            OfficeId = 2,
                            Price = 4500m,
                            PurchaseDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Sony",
                            Model = "XPeria 7",
                            OfficeId = 2,
                            Price = 3000m,
                            PurchaseDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Sony",
                            Model = "XPeria 7",
                            OfficeId = 2,
                            Price = 3000m,
                            PurchaseDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Siemens",
                            Model = "Brick",
                            OfficeId = 3,
                            Price = 220m,
                            PurchaseDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Smartphone"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Dell",
                            Model = "Desktop 900",
                            OfficeId = 1,
                            Price = 100m,
                            PurchaseDate = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Dell",
                            Model = "Desktop 900",
                            OfficeId = 1,
                            Price = 100m,
                            PurchaseDate = new DateTime(2019, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Lenovo",
                            Model = "X100",
                            OfficeId = 1,
                            Price = 300m,
                            PurchaseDate = new DateTime(2020, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Lenovo",
                            Model = "X200",
                            OfficeId = 1,
                            Price = 300m,
                            PurchaseDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Lenovo",
                            Model = "X300",
                            OfficeId = 1,
                            Price = 500m,
                            PurchaseDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Dell",
                            Model = "Optiplex 100",
                            OfficeId = 2,
                            Price = 1500m,
                            PurchaseDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Dell",
                            Model = "Optiplex 200",
                            OfficeId = 2,
                            Price = 1400m,
                            PurchaseDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Dell",
                            Model = "Optiplex 300",
                            OfficeId = 2,
                            Price = 1300m,
                            PurchaseDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Asus",
                            Model = "ROG 600",
                            OfficeId = 3,
                            Price = 1600m,
                            PurchaseDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Asus",
                            Model = "ROG 500",
                            OfficeId = 3,
                            Price = 1200m,
                            PurchaseDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Asus",
                            Model = "ROG 500",
                            OfficeId = 3,
                            Price = 1200m,
                            PurchaseDate = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Asus",
                            Model = "ROG 500",
                            OfficeId = 3,
                            Price = 1300m,
                            PurchaseDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Computer"
                        });
                });

            modelBuilder.Entity("OfficeNameSpace.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalCurrency = "usd",
                            Name = "USA"
                        },
                        new
                        {
                            Id = 2,
                            LocalCurrency = "sek",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 3,
                            LocalCurrency = "eur",
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("AssetNameSpace.Asset", b =>
                {
                    b.HasOne("OfficeNameSpace.Office", "Office")
                        .WithMany("Assets")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeNameSpace.Office", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
